# Generated by Django 5.2.1 on 2025-06-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="this-is-a-post"),
        ),
    ]
