# Generated by Django 5.2.1 on 2025-06-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="banner.png", upload_to=""),
        ),
    ]
