# Generated by Django 5.2.1 on 2025-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="kcnp.png", upload_to=""),
        ),
    ]
